#!/bin/bash

# clang will automatically invoke GCC, but we need to make sure it finds the magic-gcc which
# ignores the riscv argument
# so make sure magic gcc is on the path
echo "starting magic clang"
SCRIPT=$(readlink -f "$0")
# Absolute path this script is in
SCRIPTDIR=$(dirname "$SCRIPT")
export PATH=$SCRIPTDIR/env2:$PATH
echo $PATH


TAGGINGLIB=/usr/local/lib/HelloIne.so

if [ -f $TAGGINGLIB ];
then
    echo "File $TAGGINGLIB exists--good"
else
    echo "LLVM pass .so file: $TAGGINGLIB does not exist."
    exit -1
fi

clang -target riscv -mriscv=RV64IAMFD -Xclang -load -Xclang $TAGGINGLIB $@
#clang -target riscv -mriscv=RV64IAMFD $@
#clang -target riscv -mriscv=RV64IAMFD $@
